### ISSUE TITLE
Angående exmination 2

### ISSUE THREAD

**Issue by 1dv449** [ehamrin/1dv449_Assignment_2#1]
Hej!

Jag har nu tittat på din laboration 2.

Antar rapporten är färdig då egen reflektion fanns. Rapporten känns snabbt ihopskriven och är för tunn, speciellt på optimeringsdelen där koppling till teori och referens helt saknas samt även många av de punkter som där skulle kunna tas upp.Förklara också bättre hur man t.ex. i SQL-injectionsdelen kan attackera applikationen.

Komplettera med följande:
- Beskriv CSRF, teori, konsekvenser, åtgärd
- Komplettera med teorikoppling till prestandaåtgärdena du har och referera dessa till litteraturen
-  Komplettera även med att på liknande sätt ta upp: cache-headers, komprimering och minifiering

Meddela oss via privat meddelande i slack eller via mejl när detta är gjort.

Det finns ett delat dokument där man kan se de olika delar som skulle kunnat tas upp i rapporten.
https://docs.google.com/document/d/1kYNrL64Od1go4z0_sZUyIG8eFAaeFcdp95MIHsRm65A/

**Comment by ehamrin** [comment]
Nu finns komplettering av uppgift 2 på:
https://github.com/ehamrin/1dv449_Assignment_2/blob/master/README.md

**Comment by 1dv449** [comment]
Bra. Det är OK. Stänger denna issue
